name: Request a Feature
description: Suggest an idea for this project
body:
  - type: checkboxes
    id: pre-flight
    attributes:
      label: Preflight Checklist
      description: "Before submitting a bug report, please make sure you've done the following:"
      options:
        - label: I have installed the [latest version of Power Query SDK](https://github.com/microsoft/vscode-powerquery-sdk/releases/latest).
          required: true
        - label: I have checked existing resources, including the [common issues](https://learn.microsoft.com/en-us/power-query/commonissues) and the [release notes](https://github.com/microsoft/vscode-powerquery-sdk/releases).
          required: true
        - label: I have searched for [similar issues](https://github.com/microsoft/vscode-powerquery-sdk/issues).
          required: true

  - type: markdown
    attributes:
      value: ---

  - type: input
    id: goal
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: input
    id: solution
    attributes:
      label: Desired Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: input
    id: alternative
    attributes:
      label: Alternatives and Workarounds
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: input
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots that can help us understand your feature request better.
