# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - main

pr:
    - main

pool:
    vmImage: "windows-latest"
variables:
    CI: "true"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "18.17.0"
      displayName: "Install Node.js"

    - task: Npm@1
      displayName: "npm clean-install"
      inputs:
          command: "ci"

    - task: Npm@1
      displayName: "audit"
      inputs:
          command: "custom"
          customCommand: "run audit"

    - task: Npm@1
      displayName: "npm unit test"
      inputs:
          command: "custom"
          customCommand: "run test:unit-test"

    - task: Npm@1
      displayName: "build VSIX"
      inputs:
          command: "custom"
          customCommand: "run vsix"

    # - task: Npm@1
    #   displayName: "npm e2e test"
    #   enabled: 'true'
    #   retryCountOnTaskFailure: 5
    #   continueOnError: 'true'
    #   inputs:
    #     command: "custom"
    #     customCommand: "run test:e2e"

    - task: PoliCheck@1
      inputs:
          inputType: "Basic"
          targetType: "F"
          targetArgument: "src"
          result: "PoliCheck.xml"

    - task: CopyFiles@2
      displayName: "copy VSIX to ArtifactStagingDirectory"
      inputs:
          contents: "$(System.DefaultWorkingDirectory)/*.vsix"
          targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      displayName: "drop ArtifactStagingDirectory"
      inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: VSIX

    - task: PublishBuildArtifacts@1
      displayName: "publish policheck results"
      inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/../_sdt/logs/PoliCheck"
          ArtifactName: PoliCheck
