name: Gated pull request
on:
    workflow_dispatch:
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: windows-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - run: node -v
            - run: npm ci
            - run: npm run audit
            - run: npm run test:unit-test
            - run: npm run vsix
            - name: retry 5 times e2e test cases
              uses: nick-fields/retry@v3
              with:
                  timeout_minutes: 10
                  max_attempts: 5
                  command: npm run test:e2e
            - name: upload VSIX to artifactory
              uses: actions/upload-artifact@v4
              with:
                  name: vsix-artifact
                  path: |
                      *.vsix
